kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: wearedevs-files
provisioner: kubernetes.io/azure-file
parameters:
  storageAccount: wearedevsstorage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: wearedevs-files
  resources:
    requests:
      storage: 5Gi
