apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wearedevs-webapp
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: wearedevs-webapp
    spec:
      containers:
      - name: wearedevs-webapp
        image: wearedevs.azurecr.io/wearedevs-webapp:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:80"
---
apiVersion: v1
kind: Service
metadata:
  name: wearedevs-webapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: wearedevs-webapp

